format = """
$time ${custom.full_dir} $git_branch $git_status $python$nodejs$rust$golang$java $status $fill$cmd_duration $battery
$character"""

[custom.full_dir]
command = 'pwd | sed "s|$HOME|~|"'
when = true
style = "bold cyan"
format = "[$output]($style)"

[time]
disabled = false
use_12hr = false
time_format = "%H:%M:%S"
style = "bold yellow"
format = "[$time]($style)"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "bold purple"

[git_status]
conflicted = "🏳"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${count}"
up_to_date = ""
staged = "++${count}"
modified = "!${count}"
untracked = "?${count}"
stashed = ""
renamed = "→${count}"
deleted = "✕${count}"

[status]
disabled = false
format = "[$symbol $status]($style)"
style = "bold red"

[cmd_duration]
format = "took [$duration]($style)"
show_milliseconds = true
min_time = 0
style = "bold yellow"

[python]
symbol = "🐍 "
style = "bold yellow"
format = "[$symbol$version]($style)"

[java]
symbol = "☕ "
style = "bold red"
format = "[$symbol$version]($style)"

[nodejs]
symbol = "⬡ "
style = "bold green"
format = "[$symbol$version]($style)"

[rust]
symbol = "🦀 "
style = "bold red"
format = "[$symbol$version]($style)"

[golang]
symbol = "🐹 "
style = "bold cyan"
format = "via [$symbol$version]($style)"
[battery]
disabled = false
full_symbol = "🔋"
charging_symbol = "⚡🔋"
discharging_symbol = "󰂃 "
display = [
  { threshold = 0, style = "bold red" },
  { threshold = 35, style = "bold red" },
  { threshold = 50, style = "bold yello" },
  { threshold = 100, style = "bold green" },
]

[character]
success_symbol = "[->](bold green)"
error_symbol = "[X](bold red)"
format = "$symbol "
